# Generated by Django 5.1.15 on 2026-08-09 04:09

import django.db.models.deletion
import rooms.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=rooms.models.generate_room_code, max_length=10, unique=True)),
                ('host_token', models.CharField(default=uuid.uuid4, max_length=64)),
                ('status', models.CharField(choices=[('lobby', 'Lobby'), ('active', 'Active'), ('ended', 'Ended')], default='lobby', max_length=20)),
                ('current_question_index', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('host', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RoomSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_count', models.IntegerField(default=10)),
                ('time_per_question', models.IntegerField(default=30)),
                ('answers_per_player', models.CharField(choices=[('multiple', 'Multiple (Skribbl-style chat feed)'), ('single', 'Single (Classic 1 guess lockout)')], default='multiple', max_length=20)),
                ('answering_cooldown', models.IntegerField(default=3, help_text='Cooldown in seconds between guesses in multiple mode')),
                ('recap_duration', models.IntegerField(default=8)),
                ('answer_visibility', models.CharField(choices=[('as_submitted', 'Visible as submitted in live feed'), ('hidden_until_reveal', 'Hidden until round reveal')], default='as_submitted', max_length=25)),
                ('host_participates', models.BooleanField(default=True)),
                ('max_players', models.IntegerField(default=50)),
                ('speed_bonus_enabled', models.BooleanField(default=True)),
                ('room', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='rooms.room')),
            ],
        ),
    ]
