# Generated by Django 5.1.15 on 2026-08-09 04:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('questions', '0001_initial'),
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=50)),
                ('avatar', models.CharField(default='🧠', max_length=50)),
                ('session_token', models.CharField(default=uuid.uuid4, max_length=64)),
                ('is_host_player', models.BooleanField(default=False)),
                ('connected', models.BooleanField(default=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='rooms.room')),
            ],
            options={
                'unique_together': {('room', 'nickname')},
            },
        ),
        migrations.CreateModel(
            name='RoomQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_index', models.IntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.question')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_questions', to='rooms.room')),
            ],
            options={
                'ordering': ['order_index'],
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('is_correct', models.BooleanField(blank=True, null=True)),
                ('points_awarded', models.IntegerField(default=0)),
                ('graded_by', models.CharField(choices=[('auto', 'Auto-Graded'), ('host', 'Host Override'), ('none', 'Not Graded')], default='none', max_length=20)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='gameplay.player')),
                ('room_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='gameplay.roomquestion')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerQuestionState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solved', models.BooleanField(default=False)),
                ('solved_at', models.DateTimeField(blank=True, null=True)),
                ('attempts_count', models.IntegerField(default=0)),
                ('last_submitted_at', models.DateTimeField(blank=True, null=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_states', to='gameplay.player')),
                ('room_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_states', to='gameplay.roomquestion')),
            ],
            options={
                'unique_together': {('room_question', 'player')},
            },
        ),
    ]
